### ISSUE TITLE
Code style configuration file for auto formatting

### ISSUE THREAD

**Issue by BANKSapi** [adorsys/xs2a-gateway#95]
As a possible contributor I would like to use a configuration file for the code style used in this project, so I can use the auto format function of my IDE.

I guess files for both Eclipse and IntelliJ IDEA would be interesting. However, IDEA can also import Eclipse files, so I guess an Eclipse XML profile file would cover the majority of IDEs.

**Comment by spetrychenko** [comment]
Hi, we've added [xs2a-gateway_code_style.xml](https://github.com/adorsys/xs2a-gateway/blob/develop/xs2a-gateway_code_style.xml) for the IntelliJ IDEA and [.editorconfig](https://github.com/adorsys/xs2a-gateway/blob/develop/.editorconfig) for other editors.

**Comment by BANKSapi** [comment]
Thanks!
